# Generated by Django 4.1.3 on 2022-12-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complition',
        ),
    ]
