# Generated by Django 4.1.3 on 2022-12-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_remove_order_complition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
